function ShowTime() {
	//access system clock and get the time
	var aest = new Date();
	var localTime = aest.getTime();
	
	//obtain local UTC offset and convert to msec
	var localOffset = aest.getTimezoneOffset()*60000;
	
	//Get total UTC time in msec
	var utc = localTime + localOffset;
	//obtain and add destination UTC time offset (Brisbane, Australia +10)
	var offset = 10;
	var brisbane = utc + (3600000*offset);
	var brisDay = new Date(brisbane);
	var brisDay = brisDay.getDay();
	//Set weekend days with different opening hours
	//Set numbers representing weekend days - 0 for Sunday, 6 for Saturday
	if (brisDay==0 || brisDay==5 || brisDay==6) {
		hoursBase = 16;
		hoursBefore = 6
	}
	else {
		hoursBase = 19;
		hoursBefore = 9
	}
	
	//convert msec value (with timezone offset) to datetime string variables
	consTime = new Date(brisbane);
	var brisHours = hoursBase-consTime.getHours();
	var brisMinutes = 60-consTime.getMinutes();
	var brisSec = 60-consTime.getSeconds();
	
	//complete string for offset AEST local time
	//show CLOSED message if past closing time
	if (brisHours<0 || brisHours>hoursBefore) {
	var timeLeft = "<strong style='background-image:url()'>The SLQ building is currently closed.</strong>";
    } else if (brisHours<1 || brisHours>hoursBefore) {
        var timeLeft = "SLQ will be open for another<br /><strong style='background-image:url("+jsFileLocation+"img/wigglylines-defcon-5.svg);background-repeat:repeat-x;background-position:left 15px;background-size:10px 13px'>" +brisHours+' hrs '+brisMinutes+' min '+brisSec+' sec'+ "</strong> today";
    } else if (brisHours<2 || brisHours>hoursBefore) {
        var timeLeft = "SLQ will be open for another<br /><strong style='background-image:url("+jsFileLocation+"img/wigglylines-defcon-4.svg);background-repeat:repeat-x;background-position:left 15px;background-size:10px 13px'>" +brisHours+' hrs '+brisMinutes+' min '+brisSec+' sec'+ "</strong> today";
    } else if (brisHours<3 || brisHours>hoursBefore) {
        var timeLeft = "SLQ will be open for another<br /><strong style='background-image:url("+jsFileLocation+"img/wigglylines-defcon-3.svg);background-repeat:repeat-x;background-position:left bottom'>" +brisHours+' hrs '+brisMinutes+' min '+brisSec+' sec'+ "</strong> today";
	}
        else {
	var timeLeft = "SLQ will be open for another<br /><strong>" +brisHours+' hrs '+brisMinutes+' min '+brisSec+' sec'+ "</strong> today";
	}
	
	//output adjusted time into page
    document.getElementById("countdown").innerHTML = timeLeft;
}

//Setup variable to update on setInterval function every 1000 milliseconds
var countdown = setInterval(ShowTime ,1000);

// initialise the What's On flickity slider with jQuery
$('.main-gallery').flickity({
  // options
  cellAlign: 'left',
  contain: true,
//   setGallerySize: false,
  autoPlay: 8000,
  prevNextButtons: false,
  pageDots: true,
  wrapAround: true
});

// initialise the eResources flickity slider with jQuery
$('.eresources-gallery').flickity({
  // options
  cellAlign: 'left',
  contain: true,
//   setGallerySize: false,
  autoPlay: 10000,
  prevNextButtons: false,
  pageDots: true,
  wrapAround: true
});

// Social media buttons widget with background image generated by SLQ Instagram feed (most recent uploaded image)
var feed = new Instafeed({
    get: 'user',
    userId: '2094842558',
    accessToken: '2094842558.1677ed0.d3e45184235a4154866d053407d87571',
    sortBy: 'most-recent',
    resolution: 'low_resolution',
    limit: 1,
    clientId: '092277589b9b4837a1f960ed38c9e7bc',
    template: '<div class="insta-image" style="background-image: url({{image}});background-size: cover;height:285px;"><div class="social-buttons" id="homepage-social"> <table> <tr> <td><a href="https://twitter.com/slqld" id="homepage-social-twitter"><img src="'+jsFileLocation+'img/social/iconmonstr-twitter-4-icon.svg" class="social-icon" alt="Twitter" /></a></td><td><a href="https://www.facebook.com/statelibraryqld/" id="homepage-social-facebook"><img src="'+jsFileLocation+'img/social/iconmonstr-facebook-4-icon.svg" class="social-icon" alt="Facebook" /></a></td><td><a href="https://www.instagram.com/statelibraryqld/" id="homepage-social-instagram"><img src="'+jsFileLocation+'img/social/iconmonstr-instagram-9-icon.svg" class="social-icon active-social-data" alt="Instagram" /></a></td></tr><tr> <td><a href="https://www.flickr.com/photos/statelibraryqueensland/"><img src="'+jsFileLocation+'img/social/iconmonstr-flickr-4.svg" class="social-icon" alt="Flickr" /></a></td><td><a href="https://vimeo.com/statelibraryqld" id="homepage-social-vimeo"><img src="'+jsFileLocation+'img/social/iconmonstr-vimeo-4-icon.svg" class="social-icon" alt="Vimeo" /></a></td><td><a href="https://www.youtube.com/user/statelibraryqld" id="homepage-social-youtube"><img src="'+jsFileLocation+'img/social/iconmonstr-youtube-4-icon.svg" class="social-icon" alt="YouTube" /></a></td></tr><tr> <td><a href="https://www.historypin.org/en/person/30277"><img src="'+jsFileLocation+'img/social/iconmonstr-map-icon.svg" class="social-icon" alt="Historypin" /></a></td><td></td><td></td></tr></table> </div></div>'
});
feed.run();
            
// attach progress bar animation to object
//Credits to http://www.jqueryscript.net/loading/Custom-Viewport-Based-jQuery-Progress-Bar-Plugin-Progressbar-js.html

// $('.donations').progressBar({
//       height : "30",
//       backgroundColor : "#E0E0E0",
//       shadow : false,
//       percentage : true,
//       border : false,
//       animation : true,
//       animateTarget : true,
//       barColor : "black",
//  });


// jQuery toggle for other sites buttons
// RA 2016/06/10 changed the function so that clickable area is isolated and uses ASCCI toggle characters, not bg images
  $(document).ready(function($) {
    $('.otherSites').find('.accordion-toggle span').click(function(){

      //Expand or collapse this panel
      $(this.parentNode).next().slideToggle('fast');

        // Determine if it's open or closed
        var toggleState = $(this).html();
        if (toggleState=="+") {
            $(this).html("-");
        } else if (toggleState=="-") {
            $(this).html("+")
        }

      //Hide the other panels
      $(".accordion-content").not($(this.parentNode).next()).slideUp('fast');

        //Find change the icon of any open panels back to closed
        if($('.otherSites').find('.accordion-content span').html("-")){
            $(".toggleIcon").not($(this)).html("+")
        }
    });
  });
